services:
  frontend:
    image: garmin-tracker-frontend:latest
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api:8000
    volumes:
      - frontend_build:/app/.next
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  frontend_build:
    name: garmin_tracker_frontend_build
